# Generated by Django 3.2.5 on 2021-07-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormChecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='tel_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
